url: https://albertso.net
baseurl:

# Site settings
title: Albert So
email: albertyso@gmail.com
description: "Website of full stack web developer Albert So. Projects | github | LinkedIn"
footer_text: >
  Powered by <a href="https://jekyllrb.com">Jekyll</a> with <a href="https://github.com/y7kim/agency-jekyll-theme">Agency Theme</a>

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/devalberts
  - title: stack-overflow
    url: http://stackoverflow.com/users/6859629/albert-so
  - title: github
    url: https://github.com/aso4
  - title: linkedin
    url: https://www.linked.com/in/albertyso

# Build settings
markdown: kramdown
permalink: pretty
