# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://albertso.net" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Albert So
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Albert So Full Stack Web Developer" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Full Stack Web Developer</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: albertyso@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble: # "joeykirk"
  facebook: # "joeykirk"
  flickr:
  github: "aso4" # "madebymunsters/type-theme"
  google_plus:
  instagram: # "joeykirk"
  linkedin:  https://www.linkedin.com/in/albertyso # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  #http://stackexchange.com/users/9103945/albert-so
  steam:
  tumblr:
  twitter: "devalberts"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-83950009-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
