url: 127.0.0.1 #https://albertso.net
baseurl:

# Site settings
title: Albert So
email: albertyso@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
footer_text: >
  Powered by <a href="#">Jekyll</a> with <a href="#">Agency Theme</a>

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/devalberts
  - title: stack-overflow
    url: http://stackoverflow.com/users/6859629/albert-so
  - title: github
    url: https://github.com/aso4
  - title: linkedin
    url: https://www.linked.com/in/albertyso

# Build settings
markdown: kramdown
permalink: pretty
